version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2-todo-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8089:80"
    depends_on:
      - db
      - memcached
    environment:
      DB_HOST: db
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: todo_password
      MEMCACHED_HOST: memcached
    networks:
      - todo-network

  db:
    image: mariadb:10.11
    container_name: yii2-todo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    ports:
      - "3301:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todo-network

  memcached:
    image: memcached:1.6-alpine
    container_name: yii2-todo-memcached
    ports:
      - "11211:11211"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  db_data: