#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require './vendor/autoload.php';
require './vendor/yiisoft/yii2/Yii.php';

$config = require './config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);